### ISSUE TITLE
configurable alarm

### ISSUE THREAD

**Issue by kaworu** [eliostvs/tomate-alarm-plugin#2]
It would be nice if the alarm sound could be configured.

**Comment by Julien16** [comment]
(In xUbuntu) The plugin is playing the following file:
/usr/share/tomate/media/alarm.ogg
Using root privilege ("$ gksudo thunar", in my case) I did place another .ogg audio file in this folder and rename it alarm.ogg
It does the job. attached are two other alarm sounds, if it makes it easier...
[ogg files.zip](https://github.com/eliostvs/tomate-alarm-plugin/files/905985/ogg.files.zip)

**Comment by kaworu** [comment]
@Julien16 thanks for your hint. I agree that my request wasn't precise enough, as I meant (implicitely) configurable by a non-privileged user.

**Comment by eliostvs** [comment]
Hi, Sorry for the delay. I just update the alarm plugin. I'll try to do a release this week.

**Comment by eliostvs** [comment]
I did the release yesterday. In the extension tab you can choose a custom alarm file for the plugin. Feedbacks are welcome.

**Comment by Julien16** [comment]
It is crashing everytime I try to set up the alarm with a .mp3 or .ogg file. The setting window that open to choose the file freezes and an Ubuntu crash report notification pops up.
Let me know if you want any additional information.

**Comment by eliostvs** [comment]
Which version of Ubuntu and DE are you using?

**Comment by Julien16** [comment]
Ubuntu 16.04.2 LTS with Unity and Arc-dark theme.

(I will try with another machine - using xfce - later and let you know

**Comment by kaworu** [comment]
For info it is working fine for me, i3 / Ubuntu 16.04.2 LTS. Many thanks @eliostvs !

**Comment by Julien16** [comment]
can the freeze be related to the kernel version? I just try to understand why it is occurring for me... 
my kernel version: 4.4.0-77-generic
Are you using newer version?

**Comment by kaworu** [comment]
4.4.0-77-generic here too.

**Comment by Julien16** [comment]
![selection_20170516](https://cloud.githubusercontent.com/assets/15772610/26096779/4f1b5d12-3a5d-11e7-9dad-ec1a731649e9.png)
Can this help? I don't know what the flaw is... and I don't really need a fix because I can set it manually.
Don't hesitate to ask me if needed

**Comment by kaworu** [comment]
@Julien16 My first guess would be that the file URI is not properly escaped at some point. Could you try with a path without spaces, like say `/home/ju/Music/tomate-test.mp3`?

**Comment by Julien16** [comment]
@kAworu You got it!

**Comment by kaworu** [comment]
@Julien16 good news! In my humble opinion this is still a bug and it would be nice if you could open a new issue with the report you posted previously, so it can be tracked by @eliostvs :)

**Comment by Julien16** [comment]
@kAworu Done. Bien vu!

**Comment by kaworu** [comment]
Thank you @Julien16, closing this one then ;)
