### ISSUE TITLE
The program freezes when I set up the alarm plugin if filename contains 'space' character

### ISSUE THREAD

**Issue by Julien16** [eliostvs/tomate-alarm-plugin#3]
The plugin is crashing when I set up the alarm with a .mp3 or .ogg file **if the filename contains 'space' character**. The setting window that open to choose the file freezes and an Ubuntu crash report notification pops up. It mentions an invalid interpolation syntax in 'filename'.
![selection_20170516](https://cloud.githubusercontent.com/assets/15772610/26101015/b04ed908-3a6a-11e7-8a92-5f42f4f3067f.png)

**Comment by eliostvs** [comment]
I fixed this in the version 0.8.0 of python-tomate. Please try to update.
